import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import getConfig from 'next/config'

const axios = require('axios');
axios.defaults.headers.post['Access-Control-Allow-Origin'] = '*';


export const getServerSideProps = ({ query }) => ({
  props: query,
})

export default function Home(props) {
  console.log("PROPS", props)
  const [locationList, setLocationList] = useState([]);

  const getLocationList = async() => {
    /* ok here I need to plug into the geolocation data */ 
    const zip = 10001
    const url = `${process.env.NEXT_PUBLIC_API_TARGET}${zip}&per_page=100`
    console.log(url)
    const locations = await axios.get(
      url
    ).then(res => {
      return res.data
    }).catch(err => console.error(err));
    return locations;
  }

  useEffect(() => {
    (async() => {
      const locations = await getLocationList();
      console.log("Setting locations!", locations)
      setLocationList(locations);
      console.log(locationList)
    })()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Brewery finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beer.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brewery finder
        </h1>
        <div className="imageWrapper">
          <Image id="headerImage" width="60px" height="60px" alt="beer" src="/beer.png"/>
        </div>
        <div className="resultList">
          <ul>
             { 
                Array.isArray(locationList) && locationList.map((location, index) => {
                  return <li key={index}>{location.name}</li>
                })
              }
          </ul>
        </div>
      </main>
    </div>
  )
}
