import 'axios';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import getConfig from 'next/config'

const axios = require('axios');
axios.defaults.headers.post['Access-Control-Allow-Origin'] = '*';


export async function getServerSideProps({ query }) {
  console.log("QUERY IN SERVER SIDE PROPS", query)
  return {
    props: {
      query: query,
    }
  }
}

export default function Home({ query }) {
  // we will use NY, NY in lieu of location data from middleware
  const url = `${process.env.NEXT_PUBLIC_BASE_URL}/api/locations`
  const [locations, setLocations] = useState([]);

  useEffect(() => {
    (async() => {
      const response = await axios.get(
        url,
        { 
          params: { 
            latitude: query.latitude, 
            longitude: query.longitude  
          }
        }
      ).then(res => setLocations(res.data));
    })()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Brewery finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/beer.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Brewery finder 
        </h1>
        <div className="imageWrapper">
          <Image id="headerImage" width="60px" height="60px" alt="beer" src="/beer.png"/>
        </div>
        <div className="resultList">
          <ul>
             { 
                locations.map((location, index) => {
                  return <li key={index}>{location.name}</li>
                })
              }
          </ul>
        </div>
      </main>
    </div>
  )
}
